### ISSUE TITLE
Geth file

### ISSUE THREAD

**Issue by Nefelum** [fluxx03/ETH-Account-Cracking-3.0#1]
curl -X POST 127.0.0.1:3334  -H "Content-Type: application/json"  --data  ' { "jsonrpc": "2.0", "method": "eth_getBalance", "params": ["0x34a45419f5fb329aa948Fa3C50bd150Cae0D50c8", "latest"], "id": 1 } '

Get next response:
{"jsonrpc":"2.0","id":1,"result":"0x0"}

Is it normal?

**Comment by fluxx030** [comment]
yes

**Comment by fluxxset** [comment]
if there is no ETH in account the it will show 0.
